# Generated by Django 5.0.7 on 2024-07-12 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='설명')),
                ('recommend_menu', models.CharField(max_length=100, verbose_name='추천메뉴')),
                ('google_map_addr', models.CharField(max_length=200, verbose_name='구글맵주소')),
                ('tip', models.CharField(blank=True, max_length=100, null=True, verbose_name='꿀팁')),
                ('is_recommendation', models.BooleanField(default=False, verbose_name='추천항목여부')),
                ('category', models.CharField(choices=[('MEAL', '식사'), ('DESSERT', '디저트'), ('DRINK', '음료'), ('NIGHTMARKET', '야시장'), ('ETC', '기타')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='', verbose_name='썸네일')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='foods.food')),
            ],
        ),
    ]
